version: '3.1'
services:

  nginx:
    image: nginx:1-alpine
    depends_on:
      - wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/${WORDPRESS_THEME}
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/${WORDPRESS_THEME}
      - ./:/app

  cli:
    image: wordpress:cli
    env_file:
      - .env
    volumes:
      - ./bin:/opt/bin
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/${WORDPRESS_THEME}
    command: >
      sh /opt/bin/wait-for.sh mysql:3306 -t 60 -- sh /opt/bin/install.sh

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"

volumes:
  testsuite:
  wordpress:
